insert into `Moradores` (`Nome`) values ('Laura Kagami');
insert into `Moradores` (`Nome`) values ('Cadu');
insert into `Moradores` (`Nome`) values ('Giovanna');
insert into `Moradores` (`Nome`) values ('Kyuzo');
insert into `Moradores` (`Nome`) values ('Lara Secco');
insert into `Moradores` (`Nome`) values ('Lara Suave');
insert into `Moradores` (`Nome`) values ('Lavinia');
insert into `Moradores` (`Nome`) values ('Lucas Piloto');
insert into `Moradores` (`Nome`) values ('Manu');
insert into `Moradores` (`Nome`) values ('Marcus');
insert into `Moradores` (`Nome`) values ('Marina');
insert into `Moradores` (`Nome`) values ('Maurício');
insert into `Moradores` (`Nome`) values ('Pacheco');
insert into `Moradores` (`Nome`) values ('Rafael');
insert into `Moradores` (`Nome`) values ('Viny');
insert into `Moradores` (`Nome`) values ('Aleix');
insert into `Moradores` (`Nome`) values ('Malena');
insert into `Moradores` (`Nome`) values ('Mildred');
insert into `Moradores` (`Nome`) values ('Sofía');
insert into `Moradores` (`Nome`) values ('Hugo');
insert into `Moradores` (`Nome`) values ('Arthur');
insert into `Moradores` (`Nome`) values ('Diogo');
insert into `Moradores` (`Nome`) values ('Carol');
insert into `Moradores` (`Nome`) values ('Henrique');
insert into `Moradores` (`Nome`) values ('Nicole');
insert into `Moradores` (`Nome`) values ('Leonardo');
insert into `Moradores` (`Nome`) values ('Bruno');
insert into `Moradores` (`Nome`) values ('Rafaela Jaeger');
insert into `Moradores` (`Nome`) values ('Célio');
insert into `Moradores` (`Nome`) values ('Pedro Henrique');
insert into `Moradores` (`Nome`) values ('Joaquim');
insert into `Moradores` (`Nome`) values ('Rafaela Sauner');
insert into `Moradores` (`Nome`) values ('Eduardo');
insert into `Moradores` (`Nome`) values ('Giovani');
insert into `Moradores` (`Nome`) values ('Hérika');
insert into `Moradores` (`Nome`) values ('Pedro Pereira');
insert into `Moradores` (`Nome`) values ('Rafael P');
insert into `Moradores` (`Nome`) values ('George');
insert into `Moradores` (`Nome`) values ('Fernando');
insert into `Moradores` (`Nome`) values ('Amanda');
insert into `Moradores` (`Nome`) values ('Maria');
insert into `Moradores` (`Nome`) values ('Rodrigo');
insert into `Moradores` (`Nome`) values ('Isabele');
insert into `Moradores` (`Nome`) values ('João Vitor');
insert into `Moradores` (`Nome`) values ('Raul');
insert into `Moradores` (`Nome`) values ('Lorran');

insert into `Categorias` (`tituloCategoria`) values ('Mazelado (quem mais usou plano de saúde/ficou doente)');
insert into `Categorias` (`tituloCategoria`) values ('CLT suada (quem mais se fudeu no trabalho)');
insert into `Categorias` (`tituloCategoria`) values ('Glow up do semestre (quem ficou mais bonito)');
insert into `Categorias` (`tituloCategoria`) values ('O sumido');
insert into `Categorias` (`tituloCategoria`) values ('Pessoa Revelação');
insert into `Categorias` (`tituloCategoria`) values ('Drama Queen/King');
insert into `Categorias` (`tituloCategoria`) values ('Palestrinha');
insert into `Categorias` (`tituloCategoria`) values ('Piores Decisões');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister Simpatia');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister pavio curto');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister Preguiça');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister Pavê ou Pacumê');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister Oi e tchau');
insert into `Categorias` (`tituloCategoria`) values ('Ptzeiro do rolê');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister Fogo no Parquinho');
insert into `Categorias` (`tituloCategoria`) values ('O atrasado do grupo');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister li tudo e não entendi nada');
insert into `Categorias` (`tituloCategoria`) values ('Miss/Mister li tudo mas não vou responder');
insert into `Categorias` (`tituloCategoria`) values ('Quem mais recebeu visitas no quarto');
insert into `Categorias` (`tituloCategoria`) values ('Coach da casa');
insert into `Categorias` (`tituloCategoria`) values ('Biscoiteiro');